"""
Export Service — PDF (WeasyPrint) and Excel (openpyxl) export
"""
import io
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# SPSS-style Excel formatting constants (EXACT from RESEARCH.md)
try:
    from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
    SPSS_HEADER_FONT = Font(name="Arial", bold=True, size=9)
    SPSS_HEADER_FILL = PatternFill("solid", fgColor="D9D9D9")
    SPSS_BODY_FONT = Font(name="Arial", size=9)
    SPSS_BORDER_SIDE = Side(style="thin", color="909090")
    SPSS_BORDER = Border(
        left=SPSS_BORDER_SIDE, right=SPSS_BORDER_SIDE,
        top=SPSS_BORDER_SIDE, bottom=SPSS_BORDER_SIDE
    )
except ImportError:
    pass

SPSS_TABLE_CSS = """
<style>
body { font-family: Arial, Helvetica, sans-serif; font-size: 9pt; color: #000; margin: 20px; }
h1 { font-size: 12pt; font-weight: bold; margin-bottom: 4px; }
h2 { font-size: 10pt; font-weight: bold; margin-top: 16px; margin-bottom: 4px; }
.procedure-title { font-size: 11pt; font-weight: bold; border-bottom: 2px solid #000; margin-bottom: 12px; }
table { border-collapse: collapse; font-size: 9pt; margin-bottom: 16px; }
th { background-color: #e8e8e8; border: 1px solid #b0b0b0; padding: 3px 8px; font-weight: bold; text-align: center; }
td { border: 1px solid #b0b0b0; padding: 2px 8px; text-align: right; }
td:first-child { text-align: left; }
tr:nth-child(even) { background-color: #f8f8f8; }
.footnote { font-size: 8pt; font-style: italic; color: #444; margin-top: 4px; }
</style>
"""

JINJA2_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><meta charset="utf-8">{{ css }}</head>
<body>
<h1>{{ title }}</h1>
<p style="font-size:8pt; color:#666;">Generated by Bernie-SPSS</p>
{% for block in blocks %}
<div class="output-block">
  <div class="procedure-title">{{ block.title }}{% if block.subtitle %} — {{ block.subtitle }}{% endif %}</div>
  {% if block.headers and block.rows %}
  <table>
    <thead>
      <tr>{% for h in block.headers %}<th>{{ h }}</th>{% endfor %}</tr>
    </thead>
    <tbody>
      {% for row in block.rows %}
      <tr>{% for cell in row %}<td>{{ cell if cell is not none else '.' }}</td>{% endfor %}</tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <pre style="font-size:8pt">{{ block.content | tojson(indent=2) }}</pre>
  {% endif %}
</div>
{% endfor %}
{% if include_footer %}
<hr>
<p class="footnote">Bernie-SPSS — Open-source web-based statistical software for Vietnamese economics students</p>
{% endif %}
</body>
</html>
"""


def export_pdf(output_blocks: List[Dict], title: str = "Statistical Output", include_footer: bool = True) -> bytes:
    """
    Generate PDF from output blocks using WeasyPrint + Jinja2.
    SPSS-styled pivot tables.
    """
    try:
        from weasyprint import HTML
        import jinja2

        template = jinja2.Template(JINJA2_TEMPLATE)
        html = template.render(
            css=SPSS_TABLE_CSS,
            title=title,
            blocks=output_blocks,
            include_footer=include_footer,
        )
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except Exception as e:
        logger.error(f"PDF export failed: {e}", exc_info=True)
        raise


def export_excel(output_blocks: List[Dict], title: str = "Statistical Output") -> bytes:
    """
    Generate Excel workbook from output blocks.
    Uses SPSS-style formatting: Arial 9pt, gray headers, 3-decimal number format.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Border, Side, Alignment

    wb = Workbook()
    ws = wb.active
    ws.title = "Output"

    current_row = 1

    # Title row
    title_cell = ws.cell(row=current_row, column=1, value=title)
    title_cell.font = Font(name="Arial", bold=True, size=12)
    current_row += 2

    for block in output_blocks:
        # Procedure title
        proc_cell = ws.cell(row=current_row, column=1, value=block.get("title", ""))
        subtitle = block.get("subtitle", "")
        if subtitle:
            proc_cell.value += f" — {subtitle}"
        proc_cell.font = Font(name="Arial", bold=True, size=10)
        current_row += 1

        headers = block.get("headers", [])
        rows = block.get("rows", [])

        if not headers or not rows:
            # Try to render content as raw
            content = block.get("content", {})
            if isinstance(content, dict):
                headers = list(content.keys())
                rows = [[str(v)] for v in content.values()]

        if headers:
            # Write headers
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=current_row, column=col_idx, value=str(header))
                cell.font = SPSS_HEADER_FONT
                cell.fill = SPSS_HEADER_FILL
                cell.border = SPSS_BORDER
                cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
                ws.column_dimensions[cell.column_letter].width = max(
                    12, min(30, len(str(header)) + 4)
                )
            current_row += 1

            # Write data rows
            for row_data in rows:
                for col_idx, cell_val in enumerate(row_data, 1):
                    cell = ws.cell(row=current_row, column=col_idx, value=cell_val)
                    cell.font = SPSS_BODY_FONT
                    cell.border = SPSS_BORDER
                    if isinstance(cell_val, float):
                        cell.number_format = "0.000"
                    if col_idx > 1 and isinstance(cell_val, (int, float)):
                        cell.alignment = Alignment(horizontal="right")
                    else:
                        cell.alignment = Alignment(horizontal="left")
                current_row += 1

        current_row += 2  # Gap between blocks

    # Footer
    current_row += 1
    footer_cell = ws.cell(row=current_row, column=1, value="Generated by Bernie-SPSS")
    footer_cell.font = Font(name="Arial", size=8, italic=True, color="666666")

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.read()
